name: Render Template
description: Renders file based on template and passed variables

author: Konstantin Chukhlomin <mail@chuhlomin.com>

branding:
  icon: file-text
  color: purple

inputs:
  template:
    description: Path to template
    required: true

  vars:
    description: Variables to use in template
    required: false

  vars_path:
    description: Path to YAML file with variables
    required: false

  result_path:
    description: Desired path to result file (optional)
    required: false

  timezone:
    description: Timezone to use in `date` template function
    required: false

outputs:
  result:
    description: Rendered file content

runs:
  using: docker
  image: "docker://chuhlomin/render-template:v1.10"
