name: test

on:
  push:
    branches:
      - feat/md-table
      
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test action
        uses: ./ # Uses an action in the root directory
        id: render
        with:
          template: ./testdata/template.txt
          vars: |
            name: world

      - name: Get `result` output
        run: echo "${{ steps.render.outputs.result }}"
